### ISSUE TITLE
Bug - Deleting / deactivating / modifying item names does not work

### ISSUE THREAD

**Issue by Joeytje50** [VSLCatena/marktwerking#30]
**Describe the bug**
- When I de-activate items, modify their name, or delete them altogether, it does not seem to push the changes to the database correctly. However, when I manually dig in the database, removing items does seem to work properly.

**Environment**
 - Version: v0.1.0

**Additional context**

**Comment by Kipjr** [comment]
Hi thanks for your feedback. Have you tried version 0.1.5 ?
